# Site Settings
baseurl: ""
url : "https://naye0ng.github.io"

# Blog Settings
theme_settings :
  title : Guri's BLOG
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Suhyun Kim
    description : Hello, I'm a student majoring in data analysis and now i'm studying the web.
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : Python
        value : 95  # Percent value
        
  # Icons
  icons :
    email: myksh0903@naver.com # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: naye0ng
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
