# Site Settings
baseurl: ""
url : "https://suhyun-guri.github.io"

# Blog Settings
theme_settings :
  title : Guri's BLOG
  favicon : assets/img/flame.png

  # Profile Settings
  profile :
    image : assets/img/나 그림.jpg
    username : Suhyun Kim
    description : Hello, I'm a student majoring in data analysis and now i'm studying the web.
    experience :
      - start : 2020-12-21
        end : 2021-02-02
        experience : NovaSystem, Intern
      - start : 2021-05-01
        end : 2021-12-31
        experience : Suwon Univ. Researcher
    skills : 
      - skill : Python
        value : 80  # Percent value
      - skill : SQL
        value : 10
      - skill : JavaScript
        value : 10
        
  # Icons
  icons :
    email: myksh0903@naver.com # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: suhyun-guri
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
